baseURL = "https://www.understandingreligion.org.uk/"
languageCode = "en-gb"
title = "Understanding Religion"

[params]
  cloudinary_url = "https://res.cloudinary.com/dmyrrcwjs/image/upload"

[taxonomies]
  category = "categories"
  tag = "tags"
  sourcetype = "sourcetypes"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 80

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
    [markup.tableOfContents]
      endLevel = 4
      ordered = true
      startLevel = 1