baseURL = "https://www.understandingreligion.org.uk/"
languageCode = "en-gb"
title = "Understanding Religion"

[taxonomies]
  category = "categories"
  tag = "tags"
  sourcetype = "sourcetypes"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false